### PR TITLE
Load sprintf.js via npm

### PR DESCRIPTION
**Pull request by swissspidy**
This requires the sprintf.js npm module instead of inlining it and updates the library from 0.7-beta1 to version 1.0.3. A few changes to the tests were required to accommodate for the change.

See #41.

### CODE REVIEW

**Review by SlexAxton — CHANGES_REQUESTED** [review]
Hmm. The two reasons I inline sprintf in the past were because of the `undefined` behavior here, and because it wasn't on npm at the time I wrote this :).

Would love to not have to change this undefined behavior, it's never what people want.

**Comment by swissspidy** [comment]
What do you think about throwing an error instead of just turning `undefined` into an empty string? I think it would be better to make people aware of their errors instead of suppressing them.

I'd be happy to add support for this to the sprintf library if that sounds good to you.

**Comment by SlexAxton** [comment]
Is it really an error to have empty values? I think runtime errors in
translation are never more helpful than just outputting empty strings. I'd
be ok with adding a hook to be notified of these problems, but just
erroring out and not rendering someone's text seems like an extreme
punishment for a missing variable.

**Comment by swissspidy** [comment]
@SlexAxton Just stumbled upon this again. What do you think about using the latest version of `sprintf` from npm (see also #56) and then wrap a little helper function around them to handle `undefined`? Happy to submit a PR.

**Comment by SlexAxton** [comment]
Happy to take a PR for that.

**Pull request closed without merging**
